tags: array int
description: "Returns the sum of all elements in an array of integers."
timeout: 5
distributes:
  - test.o
  - skeleton.c
  - CMakeLists.txt
commands:
  prepare: "gcc -Wall -Werror -c test.c -o test.o"
  validate: "cmake -S . -B build && cmake --build build && cd build && ctest --output-on-failure"
