Generale info:
  name: sum
  but: programmer un programme qui calcule la somme de deux int
  language: C
  # à specifier comment on note la difficulte
  difficulty: Facile
  # par defaut en min
  time: 1
  tags: ["arithmetique", "fonctions", "debutant"]

build:
  # Compilation c'est pour clone afin de compiler les tests et supprimer leurs sources codes
  Compilation: make sumClone
  # Validation pour valider et verifier la reponses
  Validation: make sumValidate
  # les programmes utilises
  Dependencies: ["gcc","make"]
  # execution du test
  Test: testSum
